// Render a .d.ts file for a ModuleScript whose return shape was
// inferred during the corpus pre-pass. The .d.ts is a durable migration
// artifact — a user porting a Roblox game off Luau can read these to
// see the inferred shape of every module the corpus exposes, and a
// hand-written TS consumer can `import M from "./Foo"` against them to
// get strict-mode type-checked code.
//
// The .d.ts references @rbxts/types (`defined`, concrete classes,
// datatype names) and is therefore only meaningful for rbxts-mode emit.
// Native-mode .d.ts shapes are out of scope here; the CLI skips
// generation when compatMode !== 'rbxts'.

import pkgJson from '../../../package.json' with { type: 'json' };
import type { ModuleIndexEntry } from './index.js';

const VERSION = (pkgJson as { version: string }).version;
const NAME = (pkgJson as { name: string }).name;

/** Build a .d.ts source string for a module. Returns null when the
 *  entry has no usable return type — the .d.ts would carry no signal
 *  and writing an empty `_default` only adds noise.
 *
 *  Output shape (mirrors the compiled .ts's `export default X`):
 *
 *      // Generated by luau2ts vX.Y.Z (do not edit).
 *      declare const _default: <inferred shape>;
 *      export default _default;
 *
 *  Anti-landmine: the inferred shape never contains a bare `unknown`.
 *  analyzeModuleReturn synthesizes `defined` / `Record<string, defined |
 *  undefined>` / concrete class names; the printed text is consumed
 *  verbatim here. If a future synthesis step regresses and starts
 *  emitting `unknown`, that bug surfaces in the .d.ts review diff, not
 *  silently in the corpus emit. */
export function renderDts(entry: ModuleIndexEntry): string | null {
  if (!entry.returnTypeText) return null;
  return (
    `// Generated by ${NAME} v${VERSION} (do not edit).\n` +
    `declare const _default: ${entry.returnTypeText};\n` +
    `export default _default;\n`
  );
}
